"""add met_value and calories_burned

Revision ID: 1b7db97ee50b
Revises: 81d4dfa2dd3e
Create Date: 2026-09-08 21:51:47.583568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b7db97ee50b'
down_revision: Union[str, Sequence[str], None] = '81d4dfa2dd3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
