"""add height to users and body_weights table

Revision ID: 24d1e773cf08
Revises: e64e84068b01
Create Date: 2026-09-05 21:27:54.502731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24d1e773cf08'
down_revision: Union[str, Sequence[str], None] = 'e64e84068b01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_weights',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('recorded_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('height_cm', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'height_cm')
    op.drop_table('body_weights')
    # ### end Alembic commands ###
