"""set unique for weight data for per each date

Revision ID: 3f78321ff639
Revises: f85f6301d4c1
Create Date: 2026-09-08 21:05:14.567752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f78321ff639'
down_revision: Union[str, Sequence[str], None] = 'f85f6301d4c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_date', 'body_weights', ['user_id', 'recorded_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_date', 'body_weights', type_='unique')
    # ### end Alembic commands ###
