"""change to met value and add calories burned

Revision ID: 81d4dfa2dd3e
Revises: 3f78321ff639
Create Date: 2026-09-08 21:51:02.622971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81d4dfa2dd3e'
down_revision: Union[str, Sequence[str], None] = '3f78321ff639'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('met_value', sa.Float(), nullable=True))
    op.drop_column('exercises', 'calories_per_minute')
    op.add_column('workout_logs', sa.Column('calories_burned', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_logs', 'calories_burned')
    op.add_column('exercises', sa.Column('calories_per_minute', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('exercises', 'met_value')
    # ### end Alembic commands ###
