"""Add start weight kg in goal

Revision ID: 940415920c5c
Revises: 37b14704e25f
Create Date: 2026-09-15 02:32:01.609621

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "940415920c5c"
down_revision: Union[str, Sequence[str], None] = "37b14704e25f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("goals", sa.Column("start_weight_kg", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("goals", "start_weight_kg")
    # ### end Alembic commands ###
