"""add fiber and sodium in food

Revision ID: ccbc9eb6ae5d
Revises: ffd13132fc8b
Create Date: 2026-09-04 21:25:21.020696

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ccbc9eb6ae5d"
down_revision: Union[str, Sequence[str], None] = "ffd13132fc8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("foods", sa.Column("fiber_g", sa.Float(), nullable=True))
    op.add_column("foods", sa.Column("sodium_mg", sa.Float(), nullable=True))
    op.add_column("foods", sa.Column("created_by_user_id", sa.UUID(), nullable=True))
    op.add_column("foods", sa.Column("is_public", sa.Boolean(), nullable=False))
    op.create_foreign_key(None, "foods", "users", ["created_by_user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("foods_created_by_user_id_fkey", "foods", type_="foreignkey")
    op.drop_column("foods", "is_public")
    op.drop_column("foods", "created_by_user_id")
    op.drop_column("foods", "sodium_mg")
    op.drop_column("foods", "fiber_g")
    # ### end Alembic commands ###
