"""rename logged_at to log_date

Revision ID: e64e84068b01
Revises: ccbc9eb6ae5d
Create Date: 2026-09-04 23:48:29.458022

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e64e84068b01"
down_revision: Union[str, Sequence[str], None] = "ccbc9eb6ae5d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "food_logs",
        sa.Column(
            "log_date",
            sa.Date(),
            server_default=sa.text("CURRENT_DATE"),
            nullable=False,
        ),
    )
    op.drop_column("food_logs", "logged_at")
    op.add_column(
        "workout_logs",
        sa.Column(
            "log_date",
            sa.Date(),
            server_default=sa.text("CURRENT_DATE"),
            nullable=False,
        ),
    )
    op.drop_column("workout_logs", "logged_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workout_logs",
        sa.Column(
            "logged_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("workout_logs", "log_date")
    op.add_column(
        "food_logs",
        sa.Column(
            "logged_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("food_logs", "log_date")
    # ### end Alembic commands ###
